### ISSUE TITLE
Update Styling to Match New DarkWarehouse Views

### ISSUE THREAD

**Issue by itstudes** [toasted-marshmallow-co/DarkWarehouse.PublicDocs#1]
- Update colours and buttons as per DarkWarehouse project (specifically new 3JS views)
- Look at styling on Docusaurus docs: https://docusaurus.io/docs/styling-layout
- Do not change principal font. I like the default Docusaurus fonts.

**Comment by Teeldinho** [comment]
- Changed the theming and styling to reflect web app
- Added TailwindCSS 
- Made some minor adjustments to test and confirm the above-mentioned steps.
